# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=30)),
                ('sem', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Facultie',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=30)),
                ('image', models.ImageField(default='static/assets/no-img.png', upload_to='static/assets/')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.BigIntegerField()),
                ('session_id', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Course', verbose_name='the related course')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Facultie', verbose_name='the related faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=300)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sem', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.BigIntegerField()),
                ('phrase', models.CharField(max_length=30)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Question', verbose_name='the related question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Question', verbose_name='the related question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Question', verbose_name='the related question'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Facultie', verbose_name='the related faculty'),
        ),
    ]
