# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='phrase',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='weight',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='question_id',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='category',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='frontend.Course', verbose_name='the related course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='faculty_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='frontend.Facultie', verbose_name='the related faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='sem',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
