# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20171030_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.BigIntegerField()),
                ('session_id', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='name',
            new_name='phrase',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='faculty_id',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.Question', verbose_name='the related question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='weight',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='feedback',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Course', verbose_name='the related course'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Faculty', verbose_name='the related faculty'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Question', verbose_name='the related question'),
        ),
    ]
