# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_faculty_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultie',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=30)),
                ('image', models.ImageField(default='static/assets/no-img.png', upload_to='static/assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=300)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Facultie', verbose_name='the related faculty'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Facultie', verbose_name='the related faculty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Question', verbose_name='the related question'),
        ),
    ]
